version: '3'
services:
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - 16686:16686
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411" # Porta padrão do Zipkin

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"    

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - zipkin
      # - jaeger

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # API Cep Validate
      - "8081:8081"  # API Orchestrator
    environment:
      - ENV=development    
    volumes:
      - .:/app
    command: ["./CEPrun"]  # Comando para executar a API