receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":4317"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:

  zipkin:  # Exporter Zipkin
    endpoint: "http://zipkin:9411/api/v2/spans"  # URL do Zipkin

  # otlp:
  #   endpoint: jaeger:4317
  #   tls:
  #     insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]